### ISSUE TITLE
IDW?

### ISSUE THREAD

**Issue by fullofcaffeine** [3nids/rasterinterpolation#8]
Thanks for the plugin. Will you ever support the IDW interpolation method?

**Comment by 3nids** [comment]
I have no intention to do so, but it should be quite straightforward for someone to do so.
It would just need to add the proper new method in https://github.com/3nids/rasterinterpolation/blob/master/core/rasterinterpolator.py

Btw, the plugin writes interpolates and write results in a vector layer, I am not sure it's what you need.
Best wishes.

**Comment by fullofcaffeine** [comment]
Hey, thanks for the reply. What's the interpolation method you're using right now? I'm mainly considering IDW because it's good at estimating values based off the values near it, and that's the use case I have.

**Comment by 3nids** [comment]
For my usage (altitude interpolation), I'm using bicubic.

**Comment by fullofcaffeine** [comment]
Thanks Denis.
